// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: monochain/mono/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	FeeBurnPercent           cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=fee_burn_percent,json=feeBurnPercent,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fee_burn_percent"`
	ValidatorRegistrationFee types.Coin                  `protobuf:"bytes,2,opt,name=validator_registration_fee,json=validatorRegistrationFee,proto3" json:"validator_registration_fee"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_23231aadd4c09edc, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetValidatorRegistrationFee() types.Coin {
	if m != nil {
		return m.ValidatorRegistrationFee
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "monochain.mono.v1.Params")
}

func init() { proto.RegisterFile("monochain/mono/v1/params.proto", fileDescriptor_23231aadd4c09edc) }

var fileDescriptor_23231aadd4c09edc = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xe3, 0x40,
	0x18, 0xc7, 0x33, 0xcb, 0x52, 0xd8, 0x2c, 0x2c, 0xdb, 0xb2, 0xb0, 0x6d, 0x17, 0xa6, 0x65, 0x4f,
	0x45, 0xe8, 0x0c, 0xd1, 0x9b, 0xc7, 0x58, 0xc4, 0x83, 0x87, 0xd2, 0xa3, 0x22, 0x61, 0x32, 0xfd,
	0x9a, 0x0c, 0x36, 0x33, 0x61, 0x32, 0x09, 0xf6, 0x15, 0x3c, 0xf9, 0x08, 0x3e, 0x82, 0x07, 0x1f,
	0xa2, 0xc7, 0xe2, 0x49, 0x3c, 0x14, 0x69, 0x41, 0x7d, 0x0c, 0x49, 0x26, 0x54, 0xbd, 0x84, 0xff,
	0xf7, 0xfd, 0xbf, 0xfc, 0xf8, 0xcf, 0xdf, 0xc5, 0x89, 0x92, 0x8a, 0xc7, 0x4c, 0x48, 0x5a, 0x2a,
	0x5a, 0x78, 0x34, 0x65, 0x9a, 0x25, 0x19, 0x49, 0xb5, 0x32, 0xaa, 0xd5, 0xdc, 0xf9, 0xa4, 0x54,
	0xa4, 0xf0, 0xba, 0x4d, 0x96, 0x08, 0xa9, 0x68, 0xf5, 0xb5, 0x57, 0xdd, 0x0e, 0x57, 0x59, 0xa2,
	0xb2, 0xa0, 0x9a, 0xa8, 0x1d, 0x6a, 0xeb, 0x4f, 0xa4, 0x22, 0x65, 0xf7, 0xa5, 0xaa, 0xb7, 0xd8,
	0xde, 0xd0, 0x90, 0x65, 0x40, 0x0b, 0x2f, 0x04, 0xc3, 0x3c, 0xca, 0x95, 0x90, 0xd6, 0xff, 0xff,
	0x82, 0xdc, 0xc6, 0xb8, 0xca, 0xd1, 0x3a, 0x77, 0x7f, 0xcf, 0x00, 0x82, 0x30, 0xd7, 0x32, 0x48,
	0x41, 0x73, 0x90, 0xa6, 0x8d, 0xfa, 0x68, 0xf0, 0xc3, 0xf7, 0x96, 0xeb, 0x9e, 0xf3, 0xb4, 0xee,
	0xfd, 0xb3, 0xb0, 0x6c, 0x7a, 0x49, 0x84, 0xa2, 0x09, 0x33, 0x31, 0x39, 0x85, 0x88, 0xf1, 0xc5,
	0x08, 0xf8, 0xc3, 0xfd, 0xd0, 0xad, 0xf3, 0x8c, 0x80, 0x4f, 0x7e, 0xcd, 0x00, 0xfc, 0x5c, 0xcb,
	0xb1, 0x05, 0xb5, 0x2e, 0xdc, 0x6e, 0xc1, 0xe6, 0x62, 0xca, 0x8c, 0xd2, 0x81, 0x86, 0x48, 0x64,
	0x46, 0x33, 0x23, 0x94, 0x0c, 0x66, 0x00, 0xed, 0x6f, 0x7d, 0x34, 0xf8, 0xb9, 0xdf, 0x21, 0x35,
	0xa0, 0x0c, 0x4b, 0xea, 0xb0, 0xe4, 0x48, 0x09, 0xe9, 0x7f, 0x2f, 0x13, 0x4c, 0xda, 0x3b, 0xc4,
	0xe4, 0x13, 0xe1, 0x18, 0xe0, 0xb0, 0xff, 0x76, 0xdb, 0x43, 0xd7, 0xaf, 0x77, 0x7b, 0x7f, 0x3f,
	0x6a, 0xbe, 0xb2, 0x45, 0xdb, 0xd7, 0xf9, 0x27, 0xcb, 0x0d, 0x46, 0xab, 0x0d, 0x46, 0xcf, 0x1b,
	0x8c, 0x6e, 0xb6, 0xd8, 0x59, 0x6d, 0xb1, 0xf3, 0xb8, 0xc5, 0xce, 0x19, 0x89, 0x84, 0x89, 0xf3,
	0x90, 0x70, 0x95, 0x54, 0x7f, 0xcc, 0x17, 0x26, 0x16, 0xb9, 0xd5, 0xc3, 0x2f, 0x28, 0xb3, 0x48,
	0x21, 0x0b, 0x1b, 0x55, 0x73, 0x07, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x49, 0xb1, 0xa6, 0xcf,
	0xd2, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.FeeBurnPercent.Equal(that1.FeeBurnPercent) {
		return false
	}
	if !this.ValidatorRegistrationFee.Equal(&that1.ValidatorRegistrationFee) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ValidatorRegistrationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.FeeBurnPercent.Size()
		i -= size
		if _, err := m.FeeBurnPercent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FeeBurnPercent.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.ValidatorRegistrationFee.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBurnPercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeBurnPercent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorRegistrationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorRegistrationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
